language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached # will start memcached

before_script:
  - composer update --dev
  - phpenv config-add build/travis/phpenv/memcached.ini

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml Storage/ Session.php Storage.php
