language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer update --dev

script:
  - ./vendor/bin/phpcs --report=full --extensions=php --standard=build/phpcs/Joomla/ruleset.xml src/
