language: php
sudo: false
dist: trusty

env:
  global:
    - SYMFONY_VERSION="3.4.*"
    - LARAVEL_VERSION="5.8.*"
    - TWIG_VERSION="2.*"
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" TWIG_VERSION="~1.34"
    - php: 7.2
      env: RUN_PHPCS="yes"
    - php: 7.2
      env: TWIG_VERSION="1.*"
    - php: 7.3
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.3
      env: SYMFONY_VERSION="4.3.*"
    - php: 7.3
      env: LARAVEL_VERSION="^6.0"
    - php: 7.3
      env: SYMFONY_VERSION="4.4.*@dev"
    - php: 7.3
      env: SYMFONY_VERSION="5.0.*@dev"
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.3
      env: SYMFONY_VERSION="5.0.*@dev"
    - php: 7.4snapshot
    - php: nightly

before_script:
  - composer self-update
  - composer require --no-update symfony/templating:${SYMFONY_VERSION}
  - composer require --no-update illuminate/events:${LARAVEL_VERSION} illuminate/filesystem:${LARAVEL_VERSION} illuminate/view:${LARAVEL_VERSION}
  - composer require --no-update twig/twig:${TWIG_VERSION}
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/; fi;
