language: php
sudo: false
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"
    - INSTALL_APC="no"
    - INSTALL_APCU="no"
    - INSTALL_MEMCACHE="no"
    - INSTALL_MEMCACHED="yes"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: INSTALL_APC="yes" INSTALL_MEMCACHE="yes"
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" INSTALL_APC="yes" INSTALL_MEMCACHE="yes"
    - php: 5.4
      env: INSTALL_APC="yes" INSTALL_MEMCACHE="yes"
    - php: 5.5
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU="yes" INSTALL_MEMCACHE="yes"
    - php: 7.0
      env: INSTALL_APCU="yes"
    - php: 7.1
      env: INSTALL_APCU="yes"
    - php: 7.1
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.2
      env: INSTALL_APCU="yes"
    - php: 7.3
      env: INSTALL_APCU="yes"
    - php: nightly
  allow_failures:
    - php: nightly

services:
  - memcached

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS
  - if [ "$INSTALL_APC" == "yes" ]; then phpenv config-add .travis/phpenv/apc.ini; fi
  - if [ "$INSTALL_APCU" == "yes" ] && [ "$TRAVIS_PHP_VERSION" = "5.*" ]; then printf "\n" | pecl install apcu-4.0.10 && phpenv config-add .travis/phpenv/apcu.ini; fi
  - if [ "$INSTALL_APCU" == "yes" ] && [ "$TRAVIS_PHP_VERSION" = "7.*" ]; then printf "\n" | pecl install apcu-beta && phpenv config-add .travis/phpenv/apcu.ini; fi
  - if [ "$INSTALL_MEMCACHE" == "yes" ]; then phpenv config-add .travis/phpenv/memcache.ini; fi
  - if [ "$INSTALL_MEMCACHED" == "yes" ]; phpenv config-add .travis/phpenv/memcached.ini; fi

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml Storage/ Session.php Storage.php; fi;
