language: php
sudo: false
dist: trusty

env:
  global:
    - SYMFONY_VERSION="2.8.*"
    - LARAVEL_VERSION="5.1.*"
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.0
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.0
      env: SYMFONY_VERSION="2.7.*"
    - php: 7.0
      env: RUN_PHPCS="yes" SYMFONY_VERSION="3.2.*"
    - php: 7.1
    - php: 7.1
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.1
      env: SYMFONY_VERSION="3.3.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*@dev"
    - php: 7.1
      env: LARAVEL_VERSION="5.3.*"
    - php: 7.1
      env: LARAVEL_VERSION="5.4.*"
    - php: 7.2
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*@dev"
    - php: 7.2
      env: LARAVEL_VERSION="5.5.*@dev"
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

before_script:
  - composer self-update
  - composer require --no-update symfony/templating:${SYMFONY_VERSION}
  - composer require --no-update illuminate/events:${LARAVEL_VERSION} illuminate/filesystem:${LARAVEL_VERSION} illuminate/view:${LARAVEL_VERSION}
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi;
